name: Convert Rules

on: [push]

jobs:
  convert_rules:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script
      run: 
        mkdir -p rules && python scripts/convert_rules.py
        
    #- name: Setup Debug Session
    #  uses: csexton/debugger-action@master
        
    - name: Set up Git
      run: |
        git config --global user.email "1924943697@qq.com"
        git config --global user.name "Qoo-330ml"

    - name: Add and commit changes
      run: |
        git add rules/*.txt
        git commit -m "Add new file"
        git push

    - name: Push changes to repository
      uses: ad-m/github-push-action@master
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        branch: main
